name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.distribution }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - amazonlinux-2
          - amazonlinux-1
          - archlinux-rolling
          - centos-6
          - centos-7
          - debian-8
          - debian-9
          - fedora-26
          - fedora-27
          - fedora-28
          - fedora-29
          - opensuse-13.2
          - opensuse-15.1
          - opensuse-15
          - oraclelinux-6
          - oraclelinux-7
          - ubuntu-12.04
          - ubuntu-14.04
          - ubuntu-16.04
          - ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.51

      - name: Build Docker image
        run: docker build --no-cache --rm --file=${{ matrix.distribution }}-puppet/Dockerfile.${{ matrix.distribution }} --tag=diodonfrost/${{ matrix.distribution }}-puppet:latest ${{ matrix.distribution }}-puppet

      - name: Test Docker image
        run: |
          container_id=$(mktemp)
          sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro diodonfrost/${{ matrix.distribution }}-puppet:latest > "${container_id}"
          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
